# Generated by Django 5.0 on 2023-12-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_deperment_semester_appuser_admission_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='admission_year',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
