# Generated by Django 5.0 on 2023-12-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_appuser_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='admission_year',
            field=models.CharField(blank=True, default='2023', max_length=4, null=True),
        ),
    ]
