# Generated by Django 5.0 on 2023-12-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_appuser_admission_year'),
        ('voteapp', '0002_rename_deparment_vote_department_remove_vote_vote_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deperment',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='deperment',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='deperment_name',
            new_name='department_name',
        ),
    ]
