# Generated by Django 5.0 on 2023-12-29 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='deparment',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_by',
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
